### ISSUE TITLE
question about the train form

### ISSUE THREAD

**Issue by orangelee89** [ucd-dare/CarDreamer#12]
Does this model support distributed parallel training on Ascend?

**Comment by HanchuZhou** [comment]
DreamerV3 is built by Jax, a framework designed for parallel computing. Parallel training should be supported by Huawei Ascend on its computing hardware.

**Comment by gaodechen** [comment]
Thank you for the question!

GPUs over 20GB capacity can already accommodate DreamerV3 models we used in the paper along with running CARLA simulation. So I would assume that by distributed parallel training you are referring to is running several environments at the same time. The bottleneck would be CARLA simulator itself as a CARLA process can only spawn one CARLA server as single trianing environment. This kind of parallel training might need a little bit more tweaking to obtain trajectories from different CARLA servers.
