### ISSUE TITLE
AttributeError: partially initialized module 'embodied' has no attribute 'Agent' (most likely due to a circular import)

### ISSUE THREAD

**Issue by wangchangquan** [ucd-dare/CarDreamer#16]
when i run the train code "bash train_dm3.sh 2000 0 --task carla_four_lane --dreamerv3.logdir ./logdir/carla_four_lane
" , i encounter this problem, How can I slove it?

[2024-10-24 20:21:21] Starting training on port 2000...
[2024-10-24 20:21:21] Training command: python -u dreamerv3/train.py --env.world.carla_port 2000 --dreamerv3.jax.policy_devices 0 --dreamerv3.jax.train_devices 0 --task carla_four_lane --dreamerv3.logdir ./logdir/carla_four_lane
[2024-10-24 20:21:21] CARLA server is not running on port 2000. Starting or restarting...
[2024-10-24 20:21:21] Waiting for CARLA server to start on port 2000...
[2024-10-24 20:21:22] Waiting for CARLA server to start on port 2000...
[2024-10-24 20:21:23] Waiting for CARLA server to start on port 2000...
[2024-10-24 20:21:24] CARLA server is up and running on port 2000.
2024-10-24 20:21:26.245586: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/chenlab/changquan/CarDreamer/dreamerv3/train.py:4 in <module>          │
│                                                                              │
│    1 import datetime                                                         │
│    2 import warnings                                                         │
│    3                                                                         │
│ ❱  4 import embodied                                                         │
│    5 import ruamel.yaml as yaml                                              │
│    6                                                                         │
│    7 import car_dreamer                                                      │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/embodied/__init__.py:8 in       │
│ <module>                                                                     │
│                                                                              │
│    5 except ImportError:                                                     │
│    6 │   pass                                                                │
│    7                                                                         │
│ ❱  8 from . import envs, replay, run                                         │
│    9 from .core import *                                                     │
│   10                                                                         │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/embodied/replay/__init__.py:2   │
│ in <module>                                                                  │
│                                                                              │
│   1 from . import limiters, selectors                                        │
│ ❱ 2 from .adversarial import AdversarialReplay                               │
│   3 from .count_based import CountBasedReplay                                │
│   4 from .curious_replay import CuriousReplay                                │
│   5 from .generic import Generic                                             │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/embodied/replay/adversarial.py: │
│ 3 in <module>                                                                │
│                                                                              │
│    1 import numpy as np                                                      │
│    2                                                                         │
│ ❱  3 from dreamerv3.embodied.replay import CuriousReplay                     │
│    4                                                                         │
│    5                                                                         │
│    6 class AdversarialReplay(CuriousReplay):                                 │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/__init__.py:6 in <module>       │
│                                                                              │
│   3                                                                          │
│   4 sys.path.append(str(pathlib.Path(__file__).parent))                      │
│   5                                                                          │
│ ❱ 6 from .agent import Agent                                                 │
│   7                                                                          │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/agent.py:19 in <module>         │
│                                                                              │
│    16                                                                        │
│    17 logger.addFilter(CheckTypesFilter())                                   │
│    18                                                                        │
│ ❱  19 from . import behaviors, jaxagent, jaxutils, nets                      │
│    20 from . import ninjax as nj                                             │
│    21                                                                        │
│    22                                                                        │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/jaxagent.py:25 in <module>      │
│                                                                              │
│    22 │   return Agent                                                       │
│    23                                                                        │
│    24                                                                        │
│ ❱  25 class JAXAgent(embodied.Agent):                                        │
│    26 │   def __init__(self, agent_cls, obs_space, act_space, step, config): │
│    27 │   │   self.config = config.jax                                       │
│    28 │   │   self.batch_size = config.batch_size                            │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: partially initialized module 'embodied' has no attribute 'Agent'
(most likely due to a circular import)
[2024-10-24 20:22:24] Training script crashed on port 2000. Restarting...
2024-10-24 20:22:25.418383: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/chenlab/changquan/CarDreamer/dreamerv3/train.py:4 in <module>          │
│                                                                              │
│    1 import datetime                                                         │
│    2 import warnings                                                         │
│    3                                                                         │
│ ❱  4 import embodied                                                         │
│    5 import ruamel.yaml as yaml                                              │
│    6                                                                         │
│    7 import car_dreamer                                                      │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/embodied/__init__.py:8 in       │
│ <module>                                                                     │
│                                                                              │
│    5 except ImportError:                                                     │
│    6 │   pass                                                                │
│    7                                                                         │
│ ❱  8 from . import envs, replay, run                                         │
│    9 from .core import *                                                     │
│   10                                                                         │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/embodied/replay/__init__.py:2   │
│ in <module>                                                                  │
│                                                                              │
│   1 from . import limiters, selectors                                        │
│ ❱ 2 from .adversarial import AdversarialReplay                               │
│   3 from .count_based import CountBasedReplay                                │
│   4 from .curious_replay import CuriousReplay                                │
│   5 from .generic import Generic                                             │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/embodied/replay/adversarial.py: │
│ 3 in <module>                                                                │
│                                                                              │
│    1 import numpy as np                                                      │
│    2                                                                         │
│ ❱  3 from dreamerv3.embodied.replay import CuriousReplay                     │
│    4                                                                         │
│    5                                                                         │
│    6 class AdversarialReplay(CuriousReplay):                                 │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/__init__.py:6 in <module>       │
│                                                                              │
│   3                                                                          │
│   4 sys.path.append(str(pathlib.Path(__file__).parent))                      │
│   5                                                                          │
│ ❱ 6 from .agent import Agent                                                 │
│   7                                                                          │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/agent.py:19 in <module>         │
│                                                                              │
│    16                                                                        │
│    17 logger.addFilter(CheckTypesFilter())                                   │
│    18                                                                        │
│ ❱  19 from . import behaviors, jaxagent, jaxutils, nets                      │
│    20 from . import ninjax as nj                                             │
│    21                                                                        │
│    22                                                                        │
│                                                                              │
│ /home/chenlab/changquan/CarDreamer/dreamerv3/jaxagent.py:25 in <module>      │
│                                                                              │
│    22 │   return Agent                                                       │
│    23                                                                        │
│    24                                                                        │
│ ❱  25 class JAXAgent(embodied.Agent):                                        │
│    26 │   def __init__(self, agent_cls, obs_space, act_space, step, config): │
│    27 │   │   self.config = config.jax                                       │
│    28 │   │   self.batch_size = config.batch_size                            │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: partially initialized module 'embodied' has no attribute 'Agent'
(most likely due to a circular import)

**Comment by gaodechen** [comment]
Hi,

Thank you for bringing this up! We have fixed the bug in a previous commit. Please pull the latest version and run training again.

**Comment by wangchangquan** [comment]
> Hi,
> 
> Thank you for bringing this up! We have fixed the bug in a previous commit. Please pull the latest version and run training again.

thank you , I run it sucessful.
