### ISSUE TITLE
replace my own model

### ISSUE THREAD

**Issue by MeL0XIA** [ucd-dare/CarDreamer#17]
This work is very helpful for MBRL autonomous driving. Thank you for sharing. I want to know how to replace my own model on the cardreamer.

**Comment by gaodechen** [comment]
Hi there!

The `create_task` function call will create a gym environment. 

```python
import car_dreamer
task, _ = car_dreamer.create_task('carla_four_lane')
```

Then you can have your MBRL algorithm interact with the env in the convential gymnasium way. Given the task name, CarDreamer will fetch task configs, handle initialization, and create a web server for visualization at CARLA port + 7000.

Here is an example.

```python
import car_dreamer
import time

task, _ = car_dreamer.create_task('carla_four_lane')
obs = task.reset()
while True:
   action = policy(obs) # try hardcoding 12 for simply going straight
   obs, reward, is_terminal, info = task.step(action)
   # ...
   if is_terminal:
      obs = task.reset()
   time.sleep(0.1)  # prevents from running too fast to visualize
```


---

Refer to the Documents for more details:

- Create task: https://car-dreamer.readthedocs.io/en/latest/quick_start.html#creating-a-task
- An example of interacting with the task env: https://car-dreamer.readthedocs.io/en/latest/quick_start.html#visualization
- Gym base env: https://github.com/ucd-dare/CarDreamer/blob/master/car_dreamer/carla_base_env.py
- [DreamerV3's training script](https://github.com/ucd-dare/CarDreamer/blob/master/dreamerv3/train.py) here is basically doing the same but with a lot more wrappers

**Comment by MeL0XIA** [comment]
Dear Author，
When I try to connect my own model to the cardreamer platform, the following prompts will appear repeatedly during the run: _Terminal condition triggered: time_exceeded, 
Reset environment Environment reset, 
Terminal condition triggered: time_exceeded, Reset environment, 
Spawn failed because of collision at spawn position_. 
And during the training, the reward is 0 and negative reward many times. How should this situation be solved?
Looking forward to your reply. : )
