### ISSUE TITLE
Waypoints in Camera obs?

### ISSUE THREAD

**Issue by andyshuo** [ucd-dare/CarDreamer#18]
Hi, 
Nice work.

I wonder is it possible to have waypoints on camera view?
I am training on pure camera view.

I understand I can couple camera view and birdeye view where the birdeye view only contains waypoints and ego vehicle. 
However, that is not really what I wanted to test on.

Is it possible to have a waypoint pm camera view?

**Comment by gaodechen** [comment]
Hi, it is possible to render waypoints on camera images in CARLA.

There needs to be a new data handlers that renders `ego_waypoints` exposed by the ego planner onto camera images. So I assume that it should be similar to [CameraHandler](https://github.com/ucd-dare/CarDreamer/blob/36eeded0709422e537bac28b180c6c7f99a1b40d/car_dreamer/toolkit/observer/handlers/sensor_handlers.py#L68), and your `get_observation` API in the new data handler will further process ego waypoints from `env_state`.

```python
def get_observation(self, env_state: Dict) -> Tuple[Dict, Dict]:
        # ...
        ego_waypoints = env_state["ego_waypoints"]
        # Render ego waypoints on cameras
```

`ego_waypoints` has been exposed by `get_state` API within waypoint-based built-in tasks so it is already available.

```python
def get_state(self):
    return {"ego_waypoints": self.waypoints, "timesteps": self._time_step}
```

To render ego planner's waypoints on images, CARLA debug helper `draw_point` can be somehting you are looking for: https://carla.readthedocs.io/en/latest/python_api/#carladebughelper

Another way is to transform coorindates to camera image's coordinate systems. There was an example script that renders bounding boxes on camera images with such transforming and it can be helpful in this case: https://github.com/carla-simulator/carla/blob/master/PythonAPI/examples/client_bounding_boxes.py
